### ISSUE TITLE
Better Config / Troubleshooting

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-docs#27]
Doc Feedback: Include a section that talks about chifra configuration, especially trueBlocks.toml for data directory paths and RPC url
I see it mentioned in the error output of the troubleshooting section, but I missed that on first glance, and it wouldn't be immediately obvious to a new user that file even exists :slight_smile:

**Comment by MattDodsonEnglish** [comment]
For posterity, I'm extracting the highlights of the recent chat about XDG dirs, which pertains directly to this issue.

Dodson:
>  How could a user find $CONFIG? Is it safe to say that mac and Ubuntu are both going to have config in ~/.local/share  ? Where else would it be?

tjayrush
> No. It is not safe to say that $CONFIG is the same on Linux and Mac. It used to be the case that everything was stored in ~/.quickBlocks, but we got this excellent issue: https://github.com/TrueBlocks/trueblocks-core/issues/1587 and changed it. Unfortunately, this means that Linux and Mac are different. 

----
So, how can users find their configs? Well, the most direct way would be to look at the code itself. The config determiner is located here:

https://github.com/TrueBlocks/trueblocks-core/blob/c03b9c6bff6aebf8ebdb395b4aafde7a88e53632/src/other/install/qb_config.cmake

```c++
set(TB_INSTALL_FOLDER "$ENV{XDG_DATA_HOME}")
if(WIN32)
    message(STATUS "Windows build is not supported yet")
elseif(APPLE)
    if ("${TB_INSTALL_FOLDER}" STREQUAL "")
        set(TB_INSTALL_FOLDER "$ENV{HOME}/Library/Application Support/TrueBlocks")
    endif()
else()
    if ("${TB_INSTALL_FOLDER}" STREQUAL "")
        set(TB_INSTALL_FOLDER "$ENV{HOME}/.local/share/trueblocks")
    endif()
endif()
message(STATUS "Installing to [" ${TB_INSTALL_FOLDER} "]")
set(DEST_PATH ${TB_INSTALL_FOLDER})
set(SOURCE_PATH "${CMAKE_SOURCE_DIR}/../../../src/other/install")
```

So, the config could be in three places:

* wherever the user has `$XDG_DATA_HOME`
* if not:
** On mac at `~/Library/Application/Support/TrueBlocks`
** On linux/*bsd at `~/.local/share/trueblocks`

Now how do we communicate this to the user?
----

In my opinion, for now, we MUST communicate this information somehow. Especially since our present interpretation of the  [XDG base dir spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) is slightly unorthodox, as was pointed out by the Nix package builder in this issue, https://github.com/TrueBlocks/trueblocks-core/issues/1614

xwvvvvwx says:
>  If these two pieces of state only can be created if needed under $XDG_DATA_HOME/trueblocks for the names db, and $XDG_CONFIG_HOME/trueblocks for trueBlocks.toml, then everything should work fine under nix (assuming that the application knows to also check $XDG_DATA_DIRS as well as $XDG_DATA_HOME for the immutable data files).

Currently, we have all data in `$XDG_DATA_HOME`, including configs. I can say as a mere casual user, I personally was surprised the `trueBlocks.toml` was in `.local/share`, and not `.config`. This is not only because that's what I was used to, absolutely not because I had any idea about the particulars of the XDG spec.

----
For now, I'm going to add information about where to find configs in sectioned-off part of the docs' "Install" (PR coming soon). In the future, there might be a better way to handle this (I'll discuss in the following comment).

**Comment by MattDodsonEnglish** [comment]
I think we can close this. I've added a section. Maybe it's not perfect, but at least it addresses the issue.
https://docs.trueblocks.io/docs/prologue/installing/#where-is-my-config-file
