### ISSUE TITLE
Giving structure to the blog

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-docs#28]
There's a large number of blog posts on my personal Medium account. I've been able to download them and convert them into MarkDown and I started adding some of them to the docs website.

I don't want to pollute the blog with all the posts, so I was wondering how hard it would be to create structure in the blog. As a start a section for Recipes and another for Explainers. Maybe more.

**Comment by MattDodsonEnglish** [comment]
Now have a start with this commit 9604b7d . However, because I'm not sure how to categorize everything, I didn't port all articles over.

For the short term, mimicing the /docs structure works. For the long term, I think a more flexible ordering would be a better solution, as I've described in this issue:
https://github.com/TrueBlocks/trueblocks-docs/issues/34
