### ISSUE TITLE
Redirects vs. Aliases for the website

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-docs#64]
https://websites.ucr.edu/alias-vs-redirect

**Comment by MattDodsonEnglish** [comment]
I think we want to just redirect content from docs.trueblocks.io to trueblocks.io. -- at this moment, I can't  think of a good reason to use an alias, can you? It creates a seemingly-duplicate pair of docs sites.

However, if you want to keep the subdomain, that's okay too. But in that case, we'd just host the landing at `trueblocks.io`, and direct the documentation links to docs.trueblocks.io.

All strategies are valid, and used by big projects. For example:
* Stripe and Linode host their docs without a subdomain, only a `/docs` path: 
     * stripe.com/docs, 
      * https://www.linode.com/docs
* Github hosts docs on a subdomain: `docs.github.com`
* Nginx, has a special _docs landing page_, at docs.nginx.com. However, some of the links therein branch off the main domain, e.g. https://nginx.org/en/docs/install.html (this is kind of strange to me; my guess is it exists for legacy reasons).

Whatever decision you choose, it'd best to just commit to it. Ideally, these URIs will be _stable TrueBlocks URIs for the next 200 years_.

Without a specified docs subdomain, we can just have everything be a path off the `trueblocks.io` URI. By "everything", I mean all content that Trueblocks has. There'd be no change in the hugo structure, only in adding a redirect from the docs.trueblocks.io, rather than aliasing it.

```txt
trueblocks.io 
  /docs
  /data-model
  /blog
  /<whatever-else-you-add-later>
 ```

 To not break old links that used the `docs.` subdomain, I believe you could add a redirect in your nginx configuration. Judging from the tutorial I found, it probably looks something like this, where `domain1.com` is replaced by `docs.trueblocks.io`
 
 ```
 /etc/nginx/sites-available/domain1.com

server {
    . . .
    server_name domain1.com;
    rewrite ^/(.*)$ http://domain2.com/$1 permanent;
    . . .
}
```

I copied that directly from this Digital Ocean tutorial, which looks pretty useful.
https://www.digitalocean.com/community/tutorials/how-to-create-temporary-and-permanent-redirects-with-nginx

**Comment by tjayrush** [comment]
As we discussed yesterday, I agree that we should not 'alias', but we should re-direct.

My concern, however, is this. What happens later when we want to create a separation between TrueBlocks the website (at https://trueblocks.io) and TrueBlocks Docs?

At first, I thought I wanted to redirect to https://trueblocks.io/docs, but when I do that, I get a weird looking page. Also, as I click on the links, it always returns to http://trueblocks.io.

Until we detangle this, I'm going to leave the 'alias' in place, but I do want to redirect, I just feel like we have to create the `docs` subfolder so once a user goes 'into the docs' they are kept there forever unless they click on the TrueBlocks logo at the top left of the page and then they are 'out of the docs' (even though they are seeing the 'landing page.'

To say this a different, perhaps more clear, way:

- There should be a landing page at http://trueblocks.io. We should be able to change this page at will without breaking docs.
- There should be a subfolder at http://trueblocks.io/docs that contains the entire documentation hierarchy.
- Once a user 'enters' the docs, his/her URL should contain the `docs` subfolder until he/she clicks on the TrueBlocks logo at the top left of the docs to be returned to the landing page.
- There may have to be a duplicate 'landing' page at both the root of the site and the root of the `docs` folder. (In other words, if we change the landing page at the root of the site, that should not change the 'landing page' at the root of the docs.

I hope that makes sense.

The motivation for this is that I will be changing the file at the root of the website in the near future (within the next six months as we release the Explorer). Having a separate subdomain (which I don't want to do, as we've discussed above) makes it easy to change the top level landing page.

 Before I switch from 'alias' to 'redirect' I have to figure out how to do this before I redirect.

**Comment by MattDodsonEnglish** [comment]
> Until we detangle this, I'm going to leave the 'alias' in place, but I do want to redirect, I just feel like we have to create the docs subfolder so once a user goes 'into the docs' they are kept there forever unless they click on the TrueBlocks logo at the top left of the page and then they are 'out of the docs' (even though they are seeing the 'landing page.'

Hey @tjayrush  go ahead and checkout http://trueblocks.io/docs . I believe I fixed "weird list" page with commit 5aa72b4bd75417ea66817254e5ea0d8296105b3b .

It'll be easy to keep this the as the "Docs landing" in the future. Alternatively, we could migrate the current docs landing to trueblocks.io/docs sometime in the future.

**Comment by tjayrush** [comment]
I'm going to close this as I removed the 'alias' from Digital Ocean. Working on re-directing now.

**Comment by tjayrush** [comment]
I reopened this because I was having trouble getting the redirect to work. I found someone who's going to help me with the redirect, so this should be done soon. Stay tuned.

**Comment by tjayrush** [comment]
Just for my information about CertBot. Saving this here.

You should test your configuration at:
https://www.ssllabs.com/ssltest/analyze.html?d=docs.trueblocks.io
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/docs.trueblocks.io/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/docs.trueblocks.io/privkey.pem
   Your cert will expire on 2021-12-08. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot again
   with the "certonly" option. To non-interactively renew *all* of
   your certificates, run "certbot renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

**Comment by tjayrush** [comment]
It took me a total of about four hours, but I think I'm done. http://docs.trueblocks.io now **redirects** to https://trueblocks.io. I cheated though and hired someone to walk me through the process. Learned a lot...

Upshot: _dig_ is magic.

@MattDodsonEnglish Can you please test the connections and close this if you think it's now working as you wish.

Thanks.

**Comment by MattDodsonEnglish** [comment]
Sweet, works perfectly. Just tried out a bunch of paths(on a fresh machine, to ensure no cache trickery).

Nice work! That docs.trueblocks.io URL might be floating around in more places than we think, so this is important.

Happy to close this,
