### ISSUE TITLE
Make white papers a bit more prominent

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-docs#78]
Currently, in order to get to the white papers, we need to click on Blog and then there's a small link that appears a bit out of place at the top of the list.

I'd like to make the papers more easily accessible. Perhaps as a 'category' in the blog or perhaps elsewhere. Not sure.

**Comment by MattDodsonEnglish** [comment]
Understood. We could make definitely make a `/blogs/papers` category, but it might crowd off up the /blog page a bit.

I don't think we are really suffering for real estate. I see a few places to put papers:

1. As a blog category, downside is it crowds a little bit,
2. At the top-left, next to Blog
3. Top Right, right of API
4. Bottom Right.

All seem pretty reasonable to me. @tjayrush If one of these looks reasonable to you, I'll put /papers there.

![image](https://user-images.githubusercontent.com/47385188/133933162-11758eaf-e97f-4160-9fab-d6a78db86102.png)

**Comment by tjayrush** [comment]
This is great, Matt. Thanks.

My preference would be (2). Unless you have reservations, please go ahead with that.

**Comment by MattDodsonEnglish** [comment]
Fixed with this commit: https://github.com/TrueBlocks/trueblocks-docs/compare/b9ebd05e6280...33993e4cec46

I still think the paper's bibliographic organization could be improved--with a date displayed, and grouped by first reverse chronological order, then alphabetically.

I actually think this index could be generated programatically using a hugo template. The way the blog list is generated now. But that's a story for another day.

**Comment by tjayrush** [comment]
> I actually think this index could be generated programatically using a hugo template. The way the blog list is generated now. But that's a story for another day.

Write an issue, baby...

**Comment by tjayrush** [comment]
> I still think the paper's bibliographic organization could be improved--with a date displayed, and grouped by first reverse chronological order, then alphabetically. 

Another issue....I'll totally forget otherwise....
